"""M2 cau hinh checklist va phan quyen ky

Revision ID: a2fd89509b25
Revises: a1b2c3d4e5f6
Create Date: 2026-08-14 03:59:40.962882
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a2fd89509b25'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_configs',
    sa.Column('contract_type_id', sa.String(length=120), nullable=False),
    sa.Column('parent_category_id', sa.String(length=120), nullable=False),
    sa.Column('config_layer', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('group', sa.String(length=16), server_default='framework', nullable=False),
    sa.Column('lifecycle', sa.String(length=16), server_default='published', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('require_template_match', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('template_file_name', sa.String(length=300), nullable=True),
    sa.Column('approval_matrix_id', sa.String(length=64), nullable=True),
    sa.Column('clauses', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ai_tiers', postgresql.JSONB(astext_type=sa.Text()), server_default='{"ruleBasedEnabled": true, "semanticEnabled": true}', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_configs')),
    sa.UniqueConstraint('config_layer', 'contract_type_id', name='uq_checklist_configs_layer_type')
    )
    op.create_index('ix_checklist_configs_parent', 'checklist_configs', ['parent_category_id'], unique=False)
    op.create_table('signing_authority_rules',
    sa.Column('business_entity_ids', postgresql.ARRAY(sa.String(length=120)), server_default='{}', nullable=False),
    sa.Column('document_category_id', sa.String(length=120), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('max_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ec_role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('personal_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telephone_number', sa.String(length=50), nullable=False),
    sa.Column('sign_type', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signing_authority_rules_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signing_authority_rules'))
    )
    op.create_index('ix_signing_rules_category', 'signing_authority_rules', ['document_category_id'], unique=False)
    op.add_column('contract_reviews', sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_reviews', 'recipients')
    op.drop_index('ix_signing_rules_category', table_name='signing_authority_rules')
    op.drop_table('signing_authority_rules')
    op.drop_index('ix_checklist_configs_parent', table_name='checklist_configs')
    op.drop_table('checklist_configs')
    # ### end Alembic commands ###
