"""khoi tao schema M1

Revision ID: 337e0b345d70
Revises: 
Create Date: 2026-08-13 14:43:11.338151
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '337e0b345d70'
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_at', 'audit_log', ['at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('catalog_items',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('parent_slug', sa.String(length=120), nullable=True),
    sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_items')),
    sa.UniqueConstraint('kind', 'slug', name='uq_catalog_items_kind_slug')
    )
    op.create_index('ix_catalog_items_kind_status', 'catalog_items', ['kind', 'status'], unique=False)
    op.create_table('document_sequences',
    sa.Column('business_entity_code', sa.String(length=64), nullable=False),
    sa.Column('year_yy', sa.String(length=2), nullable=False),
    sa.Column('last_value', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('business_entity_code', 'year_yy', name=op.f('pk_document_sequences'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('line_manager_id', sa.UUID(), nullable=True),
    sa.Column('permissions', postgresql.ARRAY(sa.String(length=32)), server_default='{}', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['line_manager_id'], ['users.id'], name=op.f('fk_users_line_manager_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('contract_templates',
    sa.Column('contract_name_slug', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mechanism', sa.String(length=32), nullable=False),
    sa.Column('protection_effective', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('open_region_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('structure_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('binding', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('field_labels', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], name=op.f('fk_contract_templates_registered_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_templates'))
    )
    op.create_index('ix_contract_templates_scope_active', 'contract_templates', ['contract_name_slug', 'is_active'], unique=False)
    op.create_table('contract_reviews',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='full', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('contract_type_id', sa.String(length=120), nullable=False),
    sa.Column('contract_type_label', sa.String(length=300), nullable=False),
    sa.Column('group', sa.String(length=16), server_default='framework', nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('intake', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('fairness', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('disclaimer_acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('econtract', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contract_reviews_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['contract_templates.id'], name=op.f('fk_contract_reviews_template_id_contract_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_reviews')),
    sa.UniqueConstraint('code', name='uq_contract_reviews_code')
    )
    op.create_index('ix_contract_reviews_owner_status', 'contract_reviews', ['owner_id', 'status'], unique=False)
    op.create_index('ix_contract_reviews_status_created', 'contract_reviews', ['status', 'created_at'], unique=False)
    op.create_table('ai_runs',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('model_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_stage', sa.String(length=48), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('checklist_config_version', sa.String(length=64), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=4, scale=2), server_default='0', nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=24), server_default='ok', nullable=False),
    sa.Column('is_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_ai_runs_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index('ix_ai_runs_review_created', 'ai_runs', ['review_id', 'created_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_chat_messages_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_chat_messages_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_review_created', 'chat_messages', ['review_id', 'created_at'], unique=False)
    op.create_table('feedback_items',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('field_id', sa.String(length=64), nullable=True),
    sa.Column('clause_label', sa.String(length=300), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_role', sa.String(length=32), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_feedback_items_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_feedback_items_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_items'))
    )
    op.create_index('ix_feedback_items_review', 'feedback_items', ['review_id'], unique=False)
    op.create_table('review_files',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_review_files_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_review_files_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_files'))
    )
    op.create_index('ix_review_files_review_kind', 'review_files', ['review_id', 'kind'], unique=False)
    op.create_table('ai_findings',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('clause_code', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_field_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='rule', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_ai_findings_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ai_runs.id'], name=op.f('fk_ai_findings_run_id_ai_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_findings'))
    )
    op.create_index('ix_ai_findings_review_group', 'ai_findings', ['review_id', 'group_name'], unique=False)
    op.create_table('ai_proposals',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('field_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_ai_proposals_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ai_runs.id'], name=op.f('fk_ai_proposals_run_id_ai_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_proposals'))
    )
    op.create_index('ix_ai_proposals_review_status', 'ai_proposals', ['review_id', 'status'], unique=False)
    op.create_table('review_versions',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('field_diff', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('feedback', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_review_versions_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['review_files.id'], name=op.f('fk_review_versions_file_id_review_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_review_versions_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_versions')),
    sa.UniqueConstraint('review_id', 'version', name='uq_review_versions_review_id_version')
    )
    op.create_table('document_fields',
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('perm_id', sa.String(length=64), nullable=False),
    sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('region_kind', sa.String(length=24), nullable=False),
    sa.Column('writable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('field_type', sa.String(length=16), server_default='text', nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('char_len', sa.Integer(), server_default='0', nullable=False),
    sa.Column('para_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('para_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('in_table', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['contract_reviews.id'], name=op.f('fk_document_fields_review_id_contract_reviews'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['review_versions.id'], name=op.f('fk_document_fields_version_id_review_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_fields')),
    sa.UniqueConstraint('version_id', 'perm_id', name='uq_document_fields_version_id_perm_id')
    )
    op.create_index('ix_document_fields_review', 'document_fields', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_fields_review', table_name='document_fields')
    op.drop_table('document_fields')
    op.drop_table('review_versions')
    op.drop_index('ix_ai_proposals_review_status', table_name='ai_proposals')
    op.drop_table('ai_proposals')
    op.drop_index('ix_ai_findings_review_group', table_name='ai_findings')
    op.drop_table('ai_findings')
    op.drop_index('ix_review_files_review_kind', table_name='review_files')
    op.drop_table('review_files')
    op.drop_index('ix_feedback_items_review', table_name='feedback_items')
    op.drop_table('feedback_items')
    op.drop_index('ix_chat_messages_review_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_ai_runs_review_created', table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index('ix_contract_reviews_status_created', table_name='contract_reviews')
    op.drop_index('ix_contract_reviews_owner_status', table_name='contract_reviews')
    op.drop_table('contract_reviews')
    op.drop_index('ix_contract_templates_scope_active', table_name='contract_templates')
    op.drop_table('contract_templates')
    op.drop_table('users')
    op.drop_table('document_sequences')
    op.drop_index('ix_catalog_items_kind_status', table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
